<a href="https://colab.research.google.com/github/JooyoungO/machineLearning/blob/main/%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 준비

In [34]:
import pandas as pd

iris = pd.read_csv('https://raw.githubusercontent.com/jmnote/zdata/master/R/iris.csv')
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

클래스 추출

In [35]:
print(pd.unique(iris['Species']))

['setosa' 'versicolor' 'virginica']


입력 데이터와 정답 데이터를 생성해보자

In [36]:
iris_input = iris[['Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']].to_numpy()
iris_target = iris['Species'].to_numpy()

print(iris_input[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


훈련 데이터와 테스트 세트로 나누자

In [37]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    iris_input, iris_target, stratify = iris_target, random_state=42)

데이터 표준화

In [38]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler() # 정규화
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

k - 최근접 이웃 알고리즘을 이용하여 훈련하고 훈련 세트와 테스트 세트에 대해 평가하자

In [39]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target)

print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.9642857142857143
0.9210526315789473


테스트 세트의 5개의 데이터에 대해서 예측과 확률을 알아보자

In [40]:
print(kn.predict(test_scaled[:5]))

['setosa' 'versicolor' 'versicolor' 'versicolor' 'setosa']


In [41]:
import numpy as np

proba = kn.predict_proba(test_scaled[:5]) # 클래스별 확률값을 반환
print(np.round(proba, decimals=4))

[[1.     0.     0.    ]
 [0.     0.6667 0.3333]
 [0.     1.     0.    ]
 [0.     1.     0.    ]
 [1.     0.     0.    ]]


In [42]:
print(kn.classes_)

['setosa' 'versicolor' 'virginica']


최적화해보자

In [43]:
kne = KNeighborsClassifier(n_neighbors=3)
kne.fit(train_scaled, train_target)
print(kne.score(train_scaled, train_target))
print(kne.score(test_scaled, test_target))

0.9642857142857143
0.9210526315789473


로지스틱 회귀를 이용하여 다중 분류 훈련 및 최적화하기

In [44]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.9821428571428571
0.9473684210526315


확률적 경사 하강법을 이용하여 다중 분류 훈련 및 최적화하기

In [51]:
from sklearn.linear_model import SGDClassifier

# 훈련
sc = SGDClassifier(loss='log_loss', max_iter=100, tol = None, random_state=42)
sc.fit(train_scaled, train_target)

print(sc.score(train_scaled, train_target))
print(sc.score(test_scaled, test_target))
print(sc.coef_, sc.intercept_)

0.9642857142857143
0.9473684210526315
[[-1.94322095  2.73505205 -3.39873149 -3.39630289]
 [-0.87403513 -1.86400016  3.60095876 -3.62830132]
 [ 2.52657294 -3.21911911 15.69703149 13.27689317]] [ -4.86483873  -2.23950392 -20.71690699]


In [50]:
from sklearn.linear_model import SGDClassifier

# 훈련
sc = SGDClassifier(loss='hinge', max_iter=100, tol = None, random_state=42)
sc.fit(train_scaled, train_target)

print(sc.score(train_scaled, train_target))
print(sc.score(test_scaled, test_target))
print(sc.coef_, sc.intercept_)

0.9553571428571429
0.9210526315789473
[[-2.19802884  1.36207872 -3.53801909 -3.09325967]
 [-0.6324395  -4.14257517  5.01851356 -5.22446882]
 [ 3.02433604 -4.26188133 20.31805558 15.53978834]] [ -6.76185042  -2.85050015 -24.63713499]
